---
http_interactions:
- request:
    method: get
    uri: https://certificates.theodi.org/datasets/info.json
    body:
      encoding: US-ASCII
      string: ''
    headers: {}
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.4.6 (Ubuntu)
      Date:
      - Tue, 28 Oct 2014 15:18:27 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"2ff1beb0f621ced5dbecd95f2652f11d"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 53ee33764fea713af74060ae638a736f
      X-Runtime:
      - '0.015017'
      X-Rack-Cache:
      - miss
    body:
      encoding: UTF-8
      string: '{"published_certificate_count":2618}'
    http_version: 
  recorded_at: Tue, 28 Oct 2014 15:18:05 GMT
recorded_with: VCR 2.8.0
