language: ruby
cache: bundler
sudo: false
rvm:
- 1.9.3
after_success:
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X DELETE -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs/tags/CURRENT"'
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X POST -d ''{"ref":"refs/tags/CURRENT","sha":"''$TRAVIS_COMMIT''"}''  --header
  "Content-Type:application/json" -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs"'
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - ! '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - METRICS_API_USERNAME: odi
  - METRICS_API_PASSWORD: somethingsecret
  - METRICS_API_BASE_URL: https://metrics.theodi.org/
  - HUBOT_USER_LIST: 'http://hubot.theodi.org/hubot/irc'
  - AIRBRAKE_API_KEY: somethingmadeup    
  - GITHUB_ORGANISATION: 'theodi'
  - GITHUB_OAUTH_TOKEN: 'oauth_token'
  - GAPPS_USER_EMAIL: nobody@example.com
  - GAPPS_PASSWORD: not_a_real_password
  - CAPSULECRM_ACCOUNT_NAME: 'whoever'
  - CAPSULECRM_API_TOKEN: 'password'
  - PRECISEMEDIA_FEED_URL: 'http://example.com/feed'
  - TRELLO_DEV_KEY: 'trello_dev_key'
  - TRELLO_MEMBER_KEY: 'trello_member_key'