---
http_interactions:
- request:
    method: get
    uri: https://www.googleapis.com/drive/v2/files/19BkVrj1x8KwYlZL2f1mNmcs6NtGwDXuTXubgISoCQBA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - ! "google_drive Ruby library/0.4.0 google-api-ruby-client/0.8.6 Mac OS X/10.10.4\n
        (gzip)"
      Content-Type:
      - ''
      Authorization:
      - Bearer ya29.lQEEJ9t4y-vc_I2FdLFh-iu5c5dMPFous5_PoItVeTAY7SQTlVfAYhPjyz5qp7Z-Mz9gAcGCHTITdw
      Cache-Control:
      - no-store
      Accept:
      - ! '*/*'
      Accept-Enc<METRICS_API_USERNAME>ng:
      - gzip
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - Wed, 17 Jun 2015 17:05:19 GMT
      Date:
      - Wed, 17 Jun 2015 17:05:19 GMT
      Cache-Control:
      - private, max-age=0, must-revalidate, no-transform
      Etag:
      - ! '"V1-oYosm7Hqin5z0Mtb-CnZdXIE/MTQzNDExNTk1MzAyNA"'
      Vary:
      - Origin
      - X-Origin
      Content-Type:
      - application/json; charset=UTF-8
      X-Content-Type-Options:
      - nosniff
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - GSE
      Alternate-Protocol:
      - 443:quic,p=1
      Content-Enc<METRICS_API_USERNAME>ng:
      - gzip
      Transfer-Enc<METRICS_API_USERNAME>ng:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAL1W63LaOBT+n6fw0Jn8KrZsMGBmmCyXNCUttN2QNLDtZIQl
        jIItOZK4pZOZvsO+4T7JSrJJCKG7ZWa3Hg8X6Vy+c3TOd/TtyCrMCEWFulVA
        nCzwqwmJceG1WiZm0Q1asyt+665q75bDePTem7hJPwlFpS/Plp3r+eB6Po66
        F6z9qdU0aljCSCt+KVy5RTZkIqm+vSPUvwc9OS626Qhdd0+d3uDTfb9zuuoP
        Zm7vvrnuN78UjLrA8eQ9oTNtYiplKuqOs1wu7YixKMYwJcIOWeIYrM7CczRc
        4RyMEsYScwol3vWFWChyZ8YRdOQUM0RsxiNHpBxDJKYYS+Ggg7w6GBF5Mhdp
        w0AXaJZlKxlj9MswTGUSG4/ZAYeM7roWIrYjIaEkYZZnBUV/xERIhyQwUsnW
        ejeue7OF5Ebv2ymNjGE5nSdjCkl8UGATjJFwFvIkQg3J5/iYoMYh0R0vGuBY
        NJo9jPqUNfVzNXx7WvVP3wypnEXJCExGnfL5xcK9heAOD8biWNw3hOeBDDWR
        qvIV2g+drtWBYjpmkCMrwZKTUFh/ff/T6qiT44LItdqX0HqFNlLGQEISPFin
        xgZM05iEKo2MOguK8qCLalnYW3kzejEc41gorW9HlmoACTnHuvcmMBb4tV6b
        EoQwfbYkufK9I8ax0FjlzvKC4KVZ0lk9sh60z1BBUHIqDAPXA265CGpFrzJw
        /brv1Uue7fu1URaXOqEJeSbsF0Gl6HoDt6Qk66WSDbzyKA9GyCvjsLXu4V0V
        UBu4bh3U6m7NLlWquX3IZxi9VHKDKigCV70DAOrmtQEAmZKYQpWlz0ROn3lR
        UQRFUB64OgStUA5yL+bkGM0MA1Bxg0c7hEaXAvPNCTznw7neMXlERKQxXPdh
        Yrydq29hXSQKQrafqtTPOc7NWIU5j7eLP55W8jLQJlUPSUylaYPicPnuzYol
        N72LU6f5+HSffrcunc7wY3DWSe4W3dARlbKTTplk9m0aFZSzBwOAiOZcNRSV
        uvIwymN6KoQU84QInYWuCRD4Kg8g8CtV3w9qJeCWykEWCk5U9zYRUhWlC7Nw
        q2O1hY71t6eWLeTFlKqjoFIL/vHVkNoqZVzq5n+saolX0gnF4p/Y4BmzZTZO
        DuWATO0N4wmUDe3PhLPdjSma/FIQ2t8LEJoSWIrpKoknRkwU2WRCQqzgzBNd
        F1s4ktjOyOJXwl7FYrU5X12vHx9rZ3+bPNVWXkE/dQ0YiGXba7d78fn8rHTj
        jVxenvX6/ZF7tszuA5trSIKzf///9cB5ikQ4G7ecZaNhyYnc0IHMqd4QRJ6p
        uzmTsLWWWKjmy3rMsAxbUsw1cZgm0dptyGNCoXWGVSNhpf/1UW4jk7HID9jo
        BR3tGMxkdijpEE4i98PfP9ymKQ26+zmpU3ba1VKlP63S6wi85KSMlP6VlfbQ
        kueDctXTbKQe9ScIQB7PLi+FWdB2ZIJ+Tk3WQ55UPZJ6eoatc6LfpOwMLgi1
        LtTAVUS1V/LAkbBr8Cdmgv+j/PeXvUl8G3uS758JrapwbkafB+VT3rq86v5X
        M8EFXlCpVUHVr9a8oFSuVVywfyZEOtg900BfdOHY9Iu+cJjbBkvXO0tZJ4k2
        pBd6km/tZJN9a0ERp75utbPsiC34BZHC8KmnzOnoVjp6OPoba9K3tdkMAAA=
    http_version: 
  recorded_at: Wed, 17 Jun 2015 17:05:19 GMT
- request:
    method: get
    uri: https://spreadsheets.google.com/feeds/worksheets/19BkVrj1x8KwYlZL2f1mNmcs6NtGwDXuTXubgISoCQBA/private/full
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - ! "google_drive Ruby library/0.4.0 google-api-ruby-client/0.8.6 Mac OS X/10.10.4\n
        (gzip)"
      Gdata-Version:
      - '3.0'
      Content-Type:
      - ''
      Authorization:
      - Bearer ya29.lQEEJ9t4y-vc_I2FdLFh-iu5c5dMPFous5_PoItVeTAY7SQTlVfAYhPjyz5qp7Z-Mz9gAcGCHTITdw
      Cache-Control:
      - no-store
      Accept:
      - ! '*/*'
      Accept-Enc<METRICS_API_USERNAME>ng:
      - gzip
  response:
    status:
      code: 200
      message: !binary |-
        T0s=
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vYXRvbSt4bWw7IGNoYXJzZXQ9VVRGLTg7IHR5cGU9ZmVl
        ZA==
      !binary "WC1Sb2JvdHMtVGFn":
      - !binary |-
        bm9pbmRleCwgbm9mb2xsb3csIG5vc25pcHBldA==
      !binary "RXhwaXJlcw==":
      - !binary |-
        V2VkLCAxNyBKdW4gMjAxNSAxNzowNToyNCBHTVQ=
      !binary "RGF0ZQ==":
      - !binary |-
        V2VkLCAxNyBKdW4gMjAxNSAxNzowNToyNCBHTVQ=
      !binary "Q2FjaGUtQ29udHJvbA==":
      - !binary |-
        cHJpdmF0ZSwgbWF4LWFnZT0wLCBtdXN0LXJldmFsaWRhdGUsIG5vLXRyYW5z
        Zm9ybQ==
      !binary "VmFyeQ==":
      - !binary |-
        QWNjZXB0LCBYLUdEYXRhLUF1dGhvcml6YXRpb24sIEdEYXRhLVZlcnNpb24=
      !binary "R2RhdGEtVmVyc2lvbg==":
      - !binary |-
        My4w
      !binary "RXRhZw==":
      - !binary |-
        Vy8iRDA0QlEza19leXQ3SW1BOVhSVlhFVXcuIg==
      !binary "U2V0LUNvb2tpZQ==":
      - !binary |-
        TklEPTY4PU5McTM0WDBMYW1qM2pCNGRCN3VjalRUdld3NVVqLTdtdzFYZFRL
        cVA1dUxXQzhULUkxVGVuVEx4blZZMnhmWk5tOVVEay0xQ2hqY3lDR2Vqdkp0
        aTZhUWV6T1h1VzNYZGc5ZTJXY1VTdjRkMjZkWC1zcV9lR3pKN3pEaFBDazVX
        O0RvbWFpbj0uZ29vZ2xlLmNvbTtQYXRoPS87RXhwaXJlcz1UaHUsIDE3LURl
        Yy0yMDE1IDE3OjA1OjI0IEdNVDtIdHRwT25seQ==
      - !binary |-
        TklEPTY4PWtsUm95WnY4M09iYWZFN1VoMm1hcjAwejgxZXNRdUVjcXhvUkRU
        cHpQY0FKRzJMcC14V3lwanRqQWZHakUzYllwaEFDSk9Xa3BsekhFNHZXcE13
        a2MxVkwtUjBZOHRzR2hUcXZSUTI2eWdpaTlKWmk0enctMEpYZXU1ZG9CMXB3
        O0RvbWFpbj0uZ29vZ2xlLmNvbTtQYXRoPS87RXhwaXJlcz1UaHUsIDE3LURl
        Yy0yMDE1IDE3OjA1OjI0IEdNVDtIdHRwT25seQ==
      !binary "UDNw":
      - !binary |-
        Q1A9IlRoaXMgaXMgbm90IGEgUDNQIHBvbGljeSEgU2VlIGh0dHA6Ly93d3cu
        Z29vZ2xlLmNvbS9zdXBwb3J0L2FjY291bnRzL2Jpbi9hbnN3ZXIucHk/aGw9
        ZW4mYW5zd2VyPTE1MTY1NyBmb3IgbW9yZSBpbmZvLiI=
      - !binary |-
        Q1A9IlRoaXMgaXMgbm90IGEgUDNQIHBvbGljeSEgU2VlIGh0dHA6Ly93d3cu
        Z29vZ2xlLmNvbS9zdXBwb3J0L2FjY291bnRzL2Jpbi9hbnN3ZXIucHk/aGw9
        ZW4mYW5zd2VyPTE1MTY1NyBmb3IgbW9yZSBpbmZvLiI=
      !binary "WC1Db250ZW50LVR5cGUtT3B0aW9ucw==":
      - !binary |-
        bm9zbmlmZg==
      !binary "WC1GcmFtZS1PcHRpb25z":
      - !binary |-
        U0FNRU9SSUdJTg==
      !binary "WC1Yc3MtUHJvdGVjdGlvbg==":
      - !binary |-
        MTsgbW9kZT1ibG9jaw==
      !binary "U2VydmVy":
      - !binary |-
        R1NF
      !binary "QWx0ZXJuYXRlLVByb3RvY29s":
      - !binary |-
        NDQzOnF1aWMscD0x
      !binary "TGFzdC1NPE1FVFJJQ1NfQVBJX1VTRVJOQU1FPmZpZWQ=":
      - !binary |-
        RnJpLCAxMiBKdW4gMjAxNSAxMzozMjozMiBHTVQ=
      !binary "Q29udGVudC1FbmM8TUVUUklDU19BUElfVVNFUk5BTUU+bmc=":
      - !binary |-
        Z3ppcA==
      !binary "VHJhbnNmZXItRW5jPE1FVFJJQ1NfQVBJX1VTRVJOQU1FPm5n":
      - !binary |-
        Y2h1bmtlZA==
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAOyX7W7bNhSGb0VAgOrHEFGyYvkjsjLH7jpvQ4u2Sermz8CK
        xzJnSlRIylL6a/ewO9yVjJLqrw3x5mwzlKCAAUM8h0fvKx6dx/YvipgZSxCS
        8mRgOpZtGpCEnNAkGpjXV9+dds2LwJ8BEENnJnJgzpVK+wjleW7lrsVFhFq2
        3UZDxWOzzunzFJL3gEU4X6fjnhXyGJ0imUKIygRZJSDHctBqX7QpL8M5xFha
        EecRg2qvTAVgIucASpb39NbbyL5ttT7TiEgfFNauPqAXdxlX52P77PKtu/gZ
        7lVnEg9703c305fXuVVHzcCnJCjLyrLu1r23i5cPRqKci8UXXU7vcnEjfnGK
        7o/5R3b7U2vmxK/jUHqv1at8PM2uptmnaPKej95eDlEq6BIrQLOMMR/p2/lZ
        SvQCCVq20z61vVOndeW4fbelP1bnzL310SrDD/VXxMW9UXmGA5+cAhEftOVk
        bdJEga+oYhC8GU+MMZbzTxwLYsSgBA2l8fuvvxljWvWUutdxhY0TssryUb3V
        ZzRZGALYwMRMi0m0G63qPtVGcJoyqu3plkRYt9U3+phNYy5gVisuD4TwcEcv
        RmoOum2rhtwRTw47EyC0crjR93etdVI2wSHa//9mOtBAyqVqsgEJbNY8fThT
        cy4CP8ExBCEWWi+2ItANCD6qFn39vCn7U+zbTaP6qE7w0arWZnL2FVeYvQOZ
        MSUD10cPhbb3SIWFmiQEisDZ2bEV8CFRemqsx2E97j5+fws3xcvry5EehpF1
        xCHI3VlHFdnB8083Qr98WVdk6uuFB+jUQTpm7im6qdWIufoK9EmJ9agMeaL0
        oe15Ac6rUD2HpAj/6ZvAqFSPOqxHDZu/Wg+BMfnfTs+q5PE8LanMMKOfa8na
        VPdkZ2mY0kZQLVrSz0jdXUSUDFq212t3zzqtxx8cFCkXKpTLlTkFhULV9bEw
        XSnY9fMCx+n5jIsYq0GppeEMWTXers7q90djdUayH3I24lmiAkcjZvu6DAqe
        fwl6VXB9rVFXYucB+kxu1Gh4rd58GFU/xY9JH+J9Jc+GPJJnIgRDG8WNxA/x
        nhd6HunnKWLHfia4sZ8cZojXfMTUGrdx0t5Dl96BdHGm40X3h9Hx6QJFMSPu
        V8JsCJMl9C4D2Ui61Kf1vAjzLzw9Rcr0bLftuK7deya0Wft5ctSpG6/55Nno
        3MZNy9v358a27QcAVEkL/gAAAP//AwCRl8wDVxkAAA==
    http_version: 
  recorded_at: Wed, 17 Jun 2015 17:05:24 GMT
- request:
    method: get
    uri: https://spreadsheets.google.com/feeds/cells/19BkVrj1x8KwYlZL2f1mNmcs6NtGwDXuTXubgISoCQBA/o3f7txu/private/full
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - ! "google_drive Ruby library/0.4.0 google-api-ruby-client/0.8.6 Mac OS X/10.10.4\n
        (gzip)"
      Gdata-Version:
      - '3.0'
      Content-Type:
      - ''
      Authorization:
      - Bearer ya29.lQEEJ9t4y-vc_I2FdLFh-iu5c5dMPFous5_PoItVeTAY7SQTlVfAYhPjyz5qp7Z-Mz9gAcGCHTITdw
      Cache-Control:
      - no-store
      Accept:
      - ! '*/*'
      Accept-Enc<METRICS_API_USERNAME>ng:
      - gzip
  response:
    status:
      code: 200
      message: !binary |-
        T0s=
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vYXRvbSt4bWw7IGNoYXJzZXQ9VVRGLTg7IHR5cGU9ZmVl
        ZA==
      !binary "WC1Sb2JvdHMtVGFn":
      - !binary |-
        bm9pbmRleCwgbm9mb2xsb3csIG5vc25pcHBldA==
      !binary "RXhwaXJlcw==":
      - !binary |-
        V2VkLCAxNyBKdW4gMjAxNSAxNzowNToyNCBHTVQ=
      !binary "RGF0ZQ==":
      - !binary |-
        V2VkLCAxNyBKdW4gMjAxNSAxNzowNToyNCBHTVQ=
      !binary "Q2FjaGUtQ29udHJvbA==":
      - !binary |-
        cHJpdmF0ZSwgbWF4LWFnZT0wLCBtdXN0LXJldmFsaWRhdGUsIG5vLXRyYW5z
        Zm9ybQ==
      !binary "VmFyeQ==":
      - !binary |-
        QWNjZXB0LCBYLUdEYXRhLUF1dGhvcml6YXRpb24sIEdEYXRhLVZlcnNpb24=
      !binary "R2RhdGEtVmVyc2lvbg==":
      - !binary |-
        My4w
      !binary "RXRhZw==":
      - !binary |-
        Vy8iRDA0QlEza19leXQ3SW1BOVhSVlhFVXcuIg==
      !binary "U2V0LUNvb2tpZQ==":
      - !binary |-
        TklEPTY4PUQyVGtnVHptRUFoM05ldl9oeFFTTGEwR2s1SU9mXzg0M2RHaVht
        aGlYeXdUVlpteXU4Y0xQODk1YXFkd2MxSmVRal9iQVJJNEpJeTZiaVZ2dmZp
        cF90RE85X1lEc1pZVTJQT1AzQS1XNGdIMWptV1dMOGpjemQ4MldtUGhQcmJS
        O0RvbWFpbj0uZ29vZ2xlLmNvbTtQYXRoPS87RXhwaXJlcz1UaHUsIDE3LURl
        Yy0yMDE1IDE3OjA1OjI0IEdNVDtIdHRwT25seQ==
      - !binary |-
        TklEPTY4PU1vUEV3dFlZZVR0OUNoVGRLUFFkUU9nV2Y5SDhncTBlN3VnWFB6
        dXZjNzBHcGtnVEpPOVNscmUzUTd2SHp0QU56OS1KY3hnT0JfLUxUTElNMk50
        bXhfaFhrVUlIS3U5UVJySkRuRFpPX0pWT2pqZWUxdWRkUUpieGh1LWIxMkVW
        O0RvbWFpbj0uZ29vZ2xlLmNvbTtQYXRoPS87RXhwaXJlcz1UaHUsIDE3LURl
        Yy0yMDE1IDE3OjA1OjI0IEdNVDtIdHRwT25seQ==
      !binary "UDNw":
      - !binary |-
        Q1A9IlRoaXMgaXMgbm90IGEgUDNQIHBvbGljeSEgU2VlIGh0dHA6Ly93d3cu
        Z29vZ2xlLmNvbS9zdXBwb3J0L2FjY291bnRzL2Jpbi9hbnN3ZXIucHk/aGw9
        ZW4mYW5zd2VyPTE1MTY1NyBmb3IgbW9yZSBpbmZvLiI=
      - !binary |-
        Q1A9IlRoaXMgaXMgbm90IGEgUDNQIHBvbGljeSEgU2VlIGh0dHA6Ly93d3cu
        Z29vZ2xlLmNvbS9zdXBwb3J0L2FjY291bnRzL2Jpbi9hbnN3ZXIucHk/aGw9
        ZW4mYW5zd2VyPTE1MTY1NyBmb3IgbW9yZSBpbmZvLiI=
      !binary "WC1Db250ZW50LVR5cGUtT3B0aW9ucw==":
      - !binary |-
        bm9zbmlmZg==
      !binary "WC1GcmFtZS1PcHRpb25z":
      - !binary |-
        U0FNRU9SSUdJTg==
      !binary "WC1Yc3MtUHJvdGVjdGlvbg==":
      - !binary |-
        MTsgbW9kZT1ibG9jaw==
      !binary "U2VydmVy":
      - !binary |-
        R1NF
      !binary "QWx0ZXJuYXRlLVByb3RvY29s":
      - !binary |-
        NDQzOnF1aWMscD0x
      !binary "TGFzdC1NPE1FVFJJQ1NfQVBJX1VTRVJOQU1FPmZpZWQ=":
      - !binary |-
        RnJpLCAxMiBKdW4gMjAxNSAxMzozMjozMiBHTVQ=
      !binary "Q29udGVudC1FbmM8TUVUUklDU19BUElfVVNFUk5BTUU+bmc=":
      - !binary |-
        Z3ppcA==
      !binary "VHJhbnNmZXItRW5jPE1FVFJJQ1NfQVBJX1VTRVJOQU1FPm5n":
      - !binary |-
        Y2h1bmtlZA==
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAOyc/XOaSBjH/xVvbq60c4287AJi0Z4aTUyaFxFtYqZzQ3Wj
        XhAoYE3ur78FxMSwpvjDZbMzzDRTdF9YePjsA/v9iv75fmGXfiI/mLtOjRPL
        AldCztidzJ1pjRuYnYMK97mu3yI0KeGaTlDjZmHoVXl+tVqVV6Ds+lNeEgSZ
        b4TugkvqVF0POX1k+ePZprqllcfugj/gAw+N+ahCEFfgxbLIp+2+W+GTJsF4
        hhZWUJ667tRGcfPpxAotPq6WtpkGLzUIPB9Zk2CGUBhE41Q2zSYv7ic+Jq40
        nVRRaOEz8ZV/92Pphp8OBdjsgbu/0UOodhcN7coYXrUHq3JSytX1+aQedRtE
        /T7Z99POo5MZ8GNk2wEvas27of+PeF85XV3boy/Srbg4X4wD5Tw8Wh1eLc2r
        5fdpt++2es0G74JbNbxf8p4//2mFiL9d2rbO4z3qSw+fGDSpS4IoHwjKgSiZ
        IqgCCf8rqxCMdD6toY/xf1PXfyjFh432PHkh8hd7Nfk9Ok6Or+vhPLRR/Qg5
        E+TrfPJJt+fOXclHdo2zbNy1g8eG9/Hg4WFZnmfP8WDxdclb+Nr6E8eNK818
        dJvsPzrDE3e8tXeLD2cIX7vxVbk1lMl+ZxpN5mE06Mfx/epa+T2K6j5jf5Wr
        Y89j8NwgZP0Y1pPDGzuI9Zy1dSgBsm/f3ECjIVrLcOb6dd2xFqg+tnw8ZKs8
        RRgqpPPxlzo++XP7Wdlfj/DpfFJB59O+HlNCNXRDyzZQsLTDoC5LOr+r7Gmj
        ILT8sIsnj/u6uNXiSYE+Daq+u2q5Syesi4rOP/0cFY5de10oxoWbzzpyQjwl
        bqb7ZDq/Ph4cDw3vutXHk/20/LqTvCG1wN6TO76MqtHclWbrKv5iR8ZWeVzG
        vdDpY1+0k0ZL2iSMseuEOFabPJJ+futYxeHcxj/OMW92nBEduMsS5qfGSVwJ
        o1LjAFeaO94yHFr2Eo86CQK3Cca6DaY+xmkHVd1FU2kYZ8bXVqi+NlGwICrm
        6DBLlImsBVs8QUZ4gjt5gts8RSHg1oHIx9L1YeV6YLuD5gOdDCUXPMUUtbM8
        NV3Ln7AFlMwIUPJOoORtoGqm0TjvX1702+8H593eoP3+nYWfcT4F7tIfo1K0
        mJB88ZtxI35r3RyI36rGTQUkmx8+cGkU89IonF+tOl+PKdGoFDTGDHayNPYv
        TbZYVBhhUdnJorLNIo4Al4QhN0wXVw2t1ab08KUWMCUrdoSHL9v9btmlcxSu
        XP+OLa5URrhSd3KlPnsI2woGlwlObtrMtnHepZW6KgVtMWPHWdparo/YYqzC
        CGOVnYxVthmLQsCtA5GXp16vvQp6R5R40gqeYoq6WZ66juP+jK/A0sCZh2yh
        pTGClrYTLW0brWfR4LLhyQnc0d2RYdinRosOcKJQEBdzdpIl7gtugPxgNvfY
        gk0UGKEtGSgRN1y0xdtjLLituOSk7PiuYwxHw/6cBmWgUMRSRQxkIDuzbKZu
        EwEjehgg6GGArIfVfrnIKHxr4b+qcaOCeOsDt45b3rtKeNFfaZdtSvgV8tla
        PsviJ0G24GNDPAME8QyQxbNaf3D2funMfyxRgEk7eFzPl7X1ej5XcpYL5M/H
        6yYSLAtcHLm82W/aMBu9/iGVe0xQqG2p2pbFT2GLPjaUNkBQ2sAOpa11MTg3
        u53+zuTXAtUW+BinQPBxZyVYbcGP+I42zo3PcFUiWpU9YLXMzslxhxKshRi3
        FuMIuZItWNmQ4gBBigNkKe41YJXi1Jof1krPHHqtPpXlUlCIfanYx3xmZUPf
        AwR9D5D1vbeYWWeG2RxdNill1kIrXGuFWVhltmBlQygEBKEQkIXC14BVjmCV
        98isZ327c9qmBGshRK6FyCys0Y9QWKKVDe0RELRHQNYeX4NWMfpJ7eb3Rrl4
        PTJ74vURJV4LHTPVMZnProzIl4AkX4Id8uUbTLBHtjFsjqwOJU0mmloKYDGm
        p1lggfYHY8iKrCAr7kZWfIZsInseqN9440ZKtp4jJ5SBBiCUFEnSZKEiaorC
        JdHLmzWvu0O72zukAiEsfAmpLwFmGOzgPthyJkBGnAmQ4EyAZGdCEgRuE4y8
        qa192pt1enSeHWFhN0jtBlmqgMoWUWzYDSDBbgDz2Q3ixCbFdoNKspm5rwRq
        dGMZRW4Pu4F4cnJMCb/CbrC2G2TxY0rBhIzYDSDBbgDp2Q32VTCnljmVr0wq
        CiYs7Aap3YB5WNmwG0CC3QAyZTe4Hxl0jHywsBukdoMsrBW2YGXDbgAJdgNI
        z25QiWCt7GU3WPUGdIx8sLAbpHYDQmYV2KKVDb8BJPgNID2/gSTEuVXYx3Fg
        NkSLjpcPFo6D1HGQ5VVjC1c2DAeQYDiA9AwHWkSrtpfdoOMd0vHywcJusLEb
        ZGllbImXEbsBJNkNIEW7QbwqnH9R+HA2MhonZ3Re1AMLu8HGbpAFVhGZshtA
        VuwGkGQ3gHnsBuIuu4EiKLKsAlUVoCZWBMAlwcv9sixkGKPhMRW3gVy4DVK3
        gZx9i3H0/niWIJQZMRvIBLOBTDYbxDHg0lDktRqcjQzDu6TjopMLq0FqNcgi
        pTBlU5cZsRrIBKuB/ILVYG0xiF8eEr/bgPQzrthrruzhNfesTsO47FN5xapa
        5LE0j6kZ6EJkLUrB/F+mjHMqI7lMJeQylZzLNnHgnoYkb04LLs3OidWnsrai
        FjktzWkEvFi7TVT/17T2HwAAAP//7J1db9owFIb/Sne1TlqlnfIR+xIQlCLW
        kRRQ4I62rIEVyBZQ2H794iTOGLalRCq2juSrVpVAUY4enT7Je47f/TqlaJ23
        tftNuPu19xbb1+V1xgb4sP4aP7rDw8/R+imMb2vtw0143Ez/0Kb/+/t6MhuF
        rR5Zbw+0nn3ic/bjZREFT2xV/4fBbfaXTx95kUvDOuvHLd9UL7RhuzxsJ8K6
        2l6xg+lw4YojcudIIneOInJ3EVx//MO1KHNZYL15Pw6GZjYsOzZwxwN3su56
        FaxwLS13kMTuHEnszlHE7i4C7Ntpf83LXBbY/fNjr+t1jABLrG1y2yQCsKPk
        Kxfb5DdMyBIktkkktkkUC2Qvgux9rUD2pNAVHNbdt83MoBDrsNxhRWgbqNYR
        ECQCSyQCS7QKbEHr+VqCbC9BhcUE0azrhd07I0ZLrNFyoxXRraFKuRMkMksk
        Mku0yqwK3VqaeK+Vj7wzt32bemb2vBPrttxtRXQBVSqPINFaItFaolVrVehC
        Gs+D8vm8xHLd6WBuJhtEreVyy6UCuq0o2j2vkqvCRDBFYrlUYrlUq+XWC8s9
        KXR5y3XdQadr5NEUtZbLLVeEFlCNmFEklksllku1Wm5d1W/TaTMoP22WWG4v
        2M07Rh5QUWu53HJFdFFNm1Ekkkslkku1Sq6K3IqDZ4ni9mD6zUw4ilrF5Yor
        abm4uMVhuFRiuFSr4So7btpwK/ltHE+6Rp4qwxcruFxw2f9I59Mvyw2qI3ZZ
        OVHQyy/0P3zZsKhGv20UfpuVucIL3ODhwcxm3OS+WbfN3VbCK6o3uKyWWGAV
        7baAVY/eNhTNtupu+Wjut4L+2BS81m5zu5XAi+rAX1ZLLPCKglvAq8dwVfCm
        xwWXPy34Lhr77fbEzEkuyX20ipsrrgReVI7LaokFXtFyC3j1aK4K3uqaOz56
        QzOr7wGs5haaC+KREqvj8uWGfTMqigGL7IJMdkGr7DYL2T0tdoW3ua/hyMyj
        5eTuWeXlyiuyC7icF7A4L8icF7Q6b1PVeVPphUrB5Z7XNjSKm9xJa73cekV+
        USWXWS2x4CuxXtBnvX8BAAD//+zdPQrDMAwF4DP5gZ1MhQwldOsPWbJ16tKh
        Q4cev7bB7WB50CIh0BUkHvgjkpLVO4ov81r3et2Pz9Ous5ab6+jqbertw2tq
        drn00kp4CfUGUfWOwss8LlrU+3gpregGuHp/6oX904alnzYCDAq8EAXv9P+6
        yzxbc7583ned/dxcOLdus26f2NmWdWHFuqCsC1HrTqPHcrXuzLPust10lnRz
        Jd26zbp9fqOpCebSTCv5JbALUeyO8hvrFHPkjTEvYdXZ1M2VdO427vb5RTKW
        XyPeBeVdiHp3lF+k+rOqROS3luHwBQAA//8DAOx741/xwgAA
    http_version: 
  recorded_at: Wed, 17 Jun 2015 17:05:24 GMT
recorded_with: VCR 2.9.3
