Reach:
  actual: B1
  sheet: 2013
  document: dashboard
  multiplier: 1

Value unlocked:
  actual: B6
  sheet: 2013
  document: dashboard
  multiplier: 1

KPI percentage:
  actual: B5
  sheet: 2013
  document: dashboard
  multiplier: 1

Active Reach:
  actual: I30
  sheet: 2013
  document: dashboard
  multiplier: 1

Passive Reach:
  actual: I31
  sheet: 2013
  document: dashboard
  multiplier: 1

Income:
  actual: B13
  sheet: 2013
  document: dashboard
  multiplier: 1

Network size:
  actual: I33
  sheet: 2013
  document: dashboard
  multiplier: 1

Commercial people trained:
  actual: B11
  target: ZZ99
  interim_target: ZZ99
  sheet: 2013
  document: dashboard
  multiplier: 1

Non-commercial people trained:
  actual: B11
  target: ZZ99
  interim_target: ZZ99
  sheet: 2013
  document: dashboard
  multiplier: 0

Total bookings:
  actual: B7
  sheet: 2013
  document: dashboard
  multiplier: 1