Affiliates:
  actual: I28
  target: ZZ99 # blank
  interim_target: ZZ99 # blank
  sheet: 2014
  document: dashboard

Active Reach:
  actual: E3
  sheet: Dashboard
  document: reach
  multiplier: 1

Passive Reach:
  actual: E8
  sheet: Dashboard
  document: reach
  multiplier: 1

Value unlocked:
  actual: B6
  sheet: 2014
  document: dashboard
  multiplier: 1

KPI percentage:
  actual: B5
  sheet: 2014
  document: dashboard
  multiplier: 1

PR Pieces:
  actual: I20
  sheet: 2014
  document: dashboard
  multiplier: 1

Events hosted:
  actual: I27
  sheet: 2014
  document: dashboard
  multiplier: 1

Network size:
  actual: I29
  sheet: 2014
  document: dashboard
  multiplier: 1

Total bookings:
  actual: B7
  sheet: 2014
  document: dashboard
  multiplier: 1

Cash reserves:
  actual: B8
  sheet: Balance sheet
  multiplier: 1

Income:
  actual: T8
  target: AM8
  interim_target: V8:AG8
  sheet: P&L + Cashflow

Grant Funding:
  actual: U7
  target: AN7
  interim_target: W7:AH7
  sheet: General grants

Commercial research bookings:
  actual: W14
  target: AP14
  interim_target: Y14:AJ14
  sheet: Research

Non-commercial research bookings:
  actual: W23
  target: AP23
  interim_target: Y23:AJ23
  sheet: Research

Commercial training bookings:
  actual: W16
  target: AP16
  interim_target: Y16:AJ16
  sheet: Training

Non-commercial training bookings:
  actual: W29
  target: AP29
  interim_target: Y29:AJ29
  sheet: Training

Commercial projects bookings:
  actual: W14
  target: AP14
  interim_target: Y14:AJ14
  sheet: Projects

Non-commercial projects bookings:
  actual: W23
  target: AP23
  interim_target: Y23:AJ23
  sheet: Projects

Commercial network bookings:
  actual: W14
  target: AP14
  interim_target: Y14:AJ14
  sheet: Network

Non-commercial network bookings:
  actual: W20
  target: AP20
  interim_target: Y20:AJ20
  sheet: Network

Headcount:
  actual: D4:O4
  target: AG4
  interim_target: V4:AG4
  sheet: OpEx
  multiplier: 1
  ytd_method: latest

Burn:
  actual: C27:N27
  sheet: P&L + Cashflow

Commercial people trained:
  actual: W15
  target: AP15
  interim_target: Y15:AJ15
  sheet: Training
  multiplier: 1

Non-commercial people trained:
  actual: W28
  target: AP28
  interim_target: Y28:AJ28
  sheet: Training
  multiplier: 1

Partners:
  actual: W7
  target: AP7
  interim_target: Y7:AJ7
  sheet: Network
  multiplier: 1

Sponsors:
  actual: W9
  target: AP9
  interim_target: Y9:AJ9
  sheet: Network
  multiplier: 1

Supporters:
  actual: W11
  target: AP11
  interim_target: Y11:AJ11
  sheet: Network
  multiplier: 1

Startups:
  actual: W18
  target: AP18
  interim_target: Y18:AJ18
  sheet: Network
  multiplier: 1

Nodes:
  actual: W16
  target: AP16
  interim_target: Y16:AJ16
  sheet: Network
  multiplier: 1

EBITDA:
  actual: C29:N29
  latest: C29:N29
  target: AM29
  interim_target: V29:AG29
  sheet: P&L + Cashflow

Variable costs:
  actual: T15
  target: AM15
  interim_target: V15:AG15
  sheet: P&L + Cashflow

Fixed costs:
  actual: T27
  target: AM27
  interim_target: V27:AG27
  sheet: P&L + Cashflow

Research costs:
  actual: T11
  target: AM11
  interim_target: V11:AG11
  sheet: P&L + Cashflow

Training costs:
  actual: T12
  target: AM12
  interim_target: V12:AG12
  sheet: P&L + Cashflow

Projects costs:
  actual: T13
  target: AM13
  interim_target: V13:AG13
  sheet: P&L + Cashflow

Network costs:
  actual: T14
  target: AM14
  interim_target: V14:AG14
  sheet: P&L + Cashflow

Staff costs:
  actual: T20
  target: AM20
  interim_target: V20:AG20
  sheet: P&L + Cashflow

Associate costs:
  actual: T21
  target: AM21
  interim_target: V21:AG21
  sheet: P&L + Cashflow

Office and operational costs:
  actual: T22
  target: AM22
  interim_target: V22:AG22
  sheet: P&L + Cashflow

Delivery costs:
  actual: T23
  target: AM23
  interim_target: V23:AG23
  sheet: P&L + Cashflow

Communications costs:
  actual: T24
  target: AM24
  interim_target: V24:AG24
  sheet: P&L + Cashflow

Professional fees costs:
  actual: T25
  target: AM25
  interim_target: V25:AG25
  sheet: P&L + Cashflow

Software costs:
  actual: T26
  target: AM26
  interim_target: V26:AG26
  sheet: P&L + Cashflow

People trained:
  actual: E4
  sheet: Dashboard
  document: reach
  multiplier: 1
