Value unlocked:
  cell_ref: F4
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

# Global Network
Network size:
  cell_ref: F19
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Members:
  actual: F20
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Nodes:
  actual: F21
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Startups:
  actual: F22
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

# Sales
Total bookings:
  actual: E41:P41
  annual_target: AE41
  ytd_target: S41:AD41
  document: 2015_financial
  sheet: P&L - programme

Active Reach:
  actual: O2
  annual_target: AB2
  ytd_target: P2:AA2
  document: 2015_non_financial
  sheet: Culture
  multiplier: 1

Passive Reach:
  actual: O3
  annual_target: AB3
  ytd_target: P3:AA3
  document: 2015_non_financial
  sheet: Culture
  multiplier: 1

People trained:
  actual: O3
  annual_target: AB3
  ytd_target: P3:AA3
  document: 2015_non_financial
  sheet: Learning
  multiplier: 1

People trained by nodes:
  actual: F16
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Trainers trained:
  actual: O5
  annual_target: AB5
  ytd_target: P5:AA5
  document: 2015_non_financial
  sheet: Learning
  multiplier: 1

Flagship stories:
  actual: O3
  annual_target: AB3
  ytd_target: P3:AA3
  sheet: Evidence
  document: 2015_non_financial
  multiplier: 1

Network bookings:
  actual: E4:P4
  annual_target: AO4
  ytd_target: X4:AI4
  document: 2015_financial
  sheet: P&L

Innovation bookings:
  actual: E5:P5
  annual_target: AO5
  ytd_target: X5:AI5
  document: 2015_financial
  sheet: P&L

Core bookings:
  actual: E6:P6
  annual_target: AO6
  ytd_target: X6:AI6
  document: 2015_financial
  sheet: P&L

Income:
  actual: E3:P3
  annual_target: AJ3
  ytd_target: S3:AD3
  document: 2015_financial
  sheet: P&L - detail

Grant Funding:
  actual: E21:P21
  annual_target: AO21
  ytd_target: X21:AI21
  document: 2015_financial
  sheet: P&L

Headcount:
  actual: E12
  annual_target: D12
  ytd_target: D12
  document: diversity
  sheet: Gender
  multiplier: 1
  ytd_method: latest

Burn:
  cell_ref: E33:P33
  document: 2015_financial
  sheet: P&L

Network costs:
  actual: E9:P9
  annual_target: AO9
  ytd_target: X9:AI9
  document: 2015_financial
  sheet: P&L

Innovation costs:
  actual: E10:P10
  annual_target: AO10
  ytd_target: X10:AI10
  document: 2015_financial
  sheet: P&L

Core costs:
  actual: E11:P11
  annual_target: AO11
  ytd_target: X11:AI11
  document: 2015_financial
  sheet: P&L

Staff costs:
  actual: E16:P16
  annual_target: AO16
  ytd_target: X16:AI16
  document: 2015_financial
  sheet: P&L

Other costs:
  actual: E17:P17
  annual_target: AO17
  ytd_target: X17:AI17
  document: 2015_financial
  sheet: P&L

EBITDA:
  actual: E20:P20
  latest: E20:P20
  annual_target: AO20
  ytd_target: X20:AI20
  document: 2015_financial
  sheet: P&L

Cash reserves:
  cell_ref: C9
  document: 2015_financial
  sheet: Balance sheet
  multiplier: 1

Visitors:
  cell_ref: G32
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

# this should possibly come from PreciseMedia...
PR reach:
  cell_ref: G30
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Offline media reach:
  cell_ref: G31
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Social media reach:
  cell_ref: G29
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

# this should come from GA...
Website visitors:
  cell_ref: G27
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Publication reads:
  cell_ref: G28
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

# this should come from eventbrite...
Events:
  cell_ref: G25
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Event attendees:
  cell_ref: G26
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1
