Value unlocked:
  actual: F4
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

# Global Network
Network size:
  actual: F19
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Members:
  actual: F20
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Nodes:
  actual: F21
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Startups:
  actual: F22
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

# Sales
Total bookings:
  actual: E41:P41
  target: AE41
  interim_target: S41:AD41
  document: 2015_financial
  sheet: P&L - programme

Active Reach:
  actual: O2
  target: AB2
  interim_target: P2:AA2
  document: 2015_non_financial
  sheet: Culture
  multiplier: 1

Passive Reach:
  actual: O3
  target: AB3
  interim_target: P3:AA3
  document: 2015_non_financial
  sheet: Culture
  multiplier: 1

People trained:
  actual: O3
  target: AB3
  interim_target: P3:AA3
  document: 2015_non_financial
  sheet: Learning
  multiplier: 1

People trained by nodes:
  actual: F16
  document: 2015_non_financial
  sheet: aggregated
  multiplier: 1

Trainers trained:
  actual: O5
  target: AB5
  interim_target: P5:AA5
  document: 2015_non_financial
  sheet: Learning
  multiplier: 1

Flagship stories:
  actual: O3
  target: AB3
  interim_target: P3:AA3
  sheet: Evidence
  document: 2015_non_financial
  multiplier: 1

Network bookings:
  actual: E4:P4
  target: AO4
  interim_target: X4:AI4
  document: 2015_financial
  sheet: P&L

Innovation bookings:
  actual: E5:P5
  target: AO5
  interim_target: X5:AI5
  document: 2015_financial
  sheet: P&L

Core bookings:
  actual: E6:P6
  target: AO6
  interim_target: X6:AI6
  document: 2015_financial
  sheet: P&L

Income:
  actual: E3:P3
  target: AJ3
  interim_target: S3:AD3
  document: 2015_financial
  sheet: P&L - detail

Grant Funding:
  actual: E21:P21
  target: AO21
  interim_target: X21:AI21
  document: 2015_financial
  sheet: P&L

Headcount:
  actual: E12
  target: D12
  interim_target: D12
  document: diversity
  sheet: Gender
  multiplier: 1
  ytd_method: latest

Burn:
  actual: E33:P33
  document: 2015_financial
  sheet: P&L

Network costs:
  actual: E9:P9
  target: AO9
  interim_target: X9:AI9
  document: 2015_financial
  sheet: P&L

Innovation costs:
  actual: E10:P10
  target: AO10
  interim_target: X10:AI10
  document: 2015_financial
  sheet: P&L

Core costs:
  actual: E11:P11
  target: AO11
  interim_target: X11:AI11
  document: 2015_financial
  sheet: P&L

Staff costs:
  actual: E16:P16
  target: AO16
  interim_target: X16:AI16
  document: 2015_financial
  sheet: P&L

Other costs:
  actual: E17:P17
  target: AO17
  interim_target: X17:AI17
  document: 2015_financial
  sheet: P&L

EBITDA:
  actual: E20:P20
  latest: E20:P20
  target: AO20
  interim_target: X20:AI20
  document: 2015_financial
  sheet: P&L

Cash reserves:
  actual: C9
  document: 2015_financial
  sheet: Balance sheet
  multiplier: 1

Visitors:
  actual: G32
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

# this should possibly come from PreciseMedia...
PR reach:
  actual: G30
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Offline media reach:
  actual: G31
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Social media reach:
  actual: G29
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

# this should come from GA...
Website visitors:
  actual: G27
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Publication reads:
  actual: G28
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

# this should come from eventbrite...
Events:
  actual: G25
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1

Event attendees:
  actual: G26
  document: 2015_non_financial
  sheet: Public dashboards
  multiplier: 1
