document_keys:

  development:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
  test:
    dashboard: 0Aon_avj5tPqbdHFSNG1HM1JiUThOV1dpeTZ3eTNsa3c
    budget: 0AsEH-bzsP1r8dG9NZlpmc2syOGQzZlN6WmktUDVmN2c
  production:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc

cell_lookups:

  2013:

    Reach:
      cell_ref: B1
      sheet: 2013
      document: dashboard
    Bookings:
      cell_ref: B4
      sheet: 2013
      document: dashboard
    Value unlocked:
      cell_ref: B3
      sheet: 2013
      document: dashboard
    KPI percentage:
      cell_ref: B2
      sheet: 2013
      document: dashboard

  2014:

    Network size:
      cell_ref: I24
      sheet: 2014
      document: dashboard
    Members:
      cell_ref: I25
      sheet: 2014
      document: dashboard
    Nodes:
      cell_ref: I26
      sheet: 2014
      document: dashboard
    Startups:
      cell_ref: I27
      sheet: 2014
      document: dashboard
    Affiliates:
      cell_ref: I28
      sheet: 2014
      document: dashboard
    Reach:
      cell_ref: B1
      sheet: 2014
      document: dashboard
    Active Reach:
      cell_ref: I21
      sheet: 2014
      document: dashboard
    Passive Reach:
      cell_ref: I22
      sheet: 2014
      document: dashboard
    Bookings:
      cell_ref: B4
      sheet: 2014
      document: dashboard
    Value unlocked:
      cell_ref: B3
      sheet: 2014
      document: dashboard
    KPI percentage:
      cell_ref: B2
      sheet: 2014
      document: dashboard
    Total income:
      cell_ref: G12
      sheet: Summary
      document: budget
    Commercial Bookings Actual:
      cell_ref: W3
      sheet: Network
      document: budget
    Commercial Bookings Target:
      cell_ref: AP3
      sheet: Network
      document: budget
    Non-commercial Bookings Actual:
      cell_ref: W4
      sheet: Network
      document: budget
    Non-commercial Bookings Target:
      cell_ref: AP4
      sheet: Network
      document: budget
    Grant Funding Actual:
      cell_ref: U7
      sheet: General grants
      document: budget
    Grant Funding Target:
      cell_ref: AN7
      sheet: General grants
      document: budget
    Research income:
      cell_ref: G15
      sheet: Summary
      document: budget
    Training income:
      cell_ref: G16
      sheet: Summary
      document: budget
    Project income:
      cell_ref: G17
      sheet: Summary
      document: budget
    Network income:
      cell_ref: G18
      sheet: Summary
      document: budget
    Commercial research income actual:
      cell_ref: W3
      sheet: Research
      document: budget
    Commercial research income target:
      cell_ref: AP3
      sheet: Research
      document: budget
    Non-commercial research income actual:
      cell_ref: W4
      sheet: Research
      document: budget
    Non-commercial research income target:
      cell_ref: AP4
      sheet: Research
      document: budget   
    Commercial training income actual:
      cell_ref: V3
      sheet: Training
      document: budget
    Commercial training income target:
      cell_ref: AO3
      sheet: Training
      document: budget
    Non-commercial training income actual:
      cell_ref: V4
      sheet: Training
      document: budget
    Non-commercial training income target:
      cell_ref: AO4
      sheet: Training
      document: budget
    Commercial projects income actual:
      cell_ref: W3
      sheet: Projects
      document: budget
    Commercial projects income target:
      cell_ref: AP3
      sheet: Projects
      document: budget
    Non-commercial projects income actual:
      cell_ref: W4
      sheet: Projects
      document: budget
    Non-commercial projects income target:
      cell_ref: AP4
      sheet: Projects
      document: budget
    Commercial network income actual:
      cell_ref: W3
      sheet: Network
      document: budget
    Commercial network income target:
      cell_ref: AP3
      sheet: Network
      document: budget
    Non-commercial network income actual:
      cell_ref: W4
      sheet: Network
      document: budget
    Non-commercial network income target:
      cell_ref: AP4
      sheet: Network
      document: budget
    Headcount actual:
      cell_ref: D4:O4
      sheet: OpEx
      document: budget
    Headcount target:
      cell_ref: V4:AG4
      sheet: OpEx
      document: budget
    Burn actual:
      cell_ref: C27:N27
      sheet: P&L + Cashflow
      document: budget
    Burn target:
      cell_ref: V27:AG27
      sheet: P&L + Cashflow
      document: budget
    Commercial people trained actual:
      cell_ref: E15:P15
      sheet: Training
      document: budget
    Commercial people trained target:
      cell_ref: X15:AI15
      sheet: Training
      document: budget
    Non-commercial people trained actual:
      cell_ref: E28:P28
      sheet: Training
      document: budget
    Non-commercial people trained target:
      cell_ref: X28:AI28
      sheet: Training
      document: budget
    Partners actual:
      cell_ref: W7
      sheet: Network
      document: budget
    Partners target:
      cell_ref: AP7
      sheet: Network
      document: budget
    Sponsors actual:
      cell_ref: W9
      sheet: Network
      document: budget
    Sponsors target:
      cell_ref: AP9
      sheet: Network
      document: budget
    Supporters actual:
      cell_ref: W11
      sheet: Network
      document: budget
    Supporters target:
      cell_ref: AP11
      sheet: Network
      document: budget
    Startups actual:
      cell_ref: W18
      sheet: Network
      document: budget
    Startups target:
      cell_ref: AP18
      sheet: Network
      document: budget
    Nodes actual:
      cell_ref: W16
      sheet: Network
      document: budget
    Nodes target:
      cell_ref: AP16
      sheet: Network
      document: budget
    EBITDA actual:
      cell_ref: C45:N45
      sheet: P&L + Cashflow
      document: budget
    EBITDA target:
      cell_ref: V45:AG45
      sheet: P&L + Cashflow
      document: budget
    Variable costs actual:
      cell_ref: C15:N15
      sheet: P&L + Cashflow
      document: budget
    Variable costs target:
      cell_ref: V15:AG15
      sheet: P&L + Cashflow
      document: budget
    Fixed costs actual:
      cell_ref: C27:N27
      sheet: P&L + Cashflow
      document: budget
    Fixed costs target:
      cell_ref: V27:AG27
      sheet: P&L + Cashflow
      document: budget
    Research costs actual:
      cell_ref: C11:N11
      sheet: P&L + Cashflow
      document: budget
    Research costs target:
      cell_ref: V11:AG11
      sheet: P&L + Cashflow
      document: budget
    Training costs actual:
      cell_ref: C12:N12
      sheet: P&L + Cashflow
      document: budget
    Training costs target:
      cell_ref: V12:AG12
      sheet: P&L + Cashflow
      document: budget
    Projects costs actual:
      cell_ref: C13:N13
      sheet: P&L + Cashflow
      document: budget
    Projects costs target:
      cell_ref: V13:AG13
      sheet: P&L + Cashflow
      document: budget
    Network costs actual:
      cell_ref: C14:N14
      sheet: P&L + Cashflow
      document: budget
    Network costs target:
      cell_ref: V14:AG14
      sheet: P&L + Cashflow
      document: budget
    Staff costs actual:
      cell_ref: C20:N20
      sheet: P&L + Cashflow
      document: budget
    Staff costs target:
      cell_ref: V20:AG20
      sheet: P&L + Cashflow
      document: budget
    Associate costs actual:
      cell_ref: C21:N21
      sheet: P&L + Cashflow
      document: budget
    Associate costs target:
      cell_ref: V21:AG21
      sheet: P&L + Cashflow
      document: budget
    Office and operational costs actual:
      cell_ref: C22:N22
      sheet: P&L + Cashflow
      document: budget
    Office and operational costs target:
      cell_ref: V22:AG22
      sheet: P&L + Cashflow
      document: budget
    Delivery costs actual:
      cell_ref: C23:N23
      sheet: P&L + Cashflow
      document: budget
    Delivery costs target:
      cell_ref: V23:AG23
      sheet: P&L + Cashflow
      document: budget
    Communications costs actual:
      cell_ref: C24:N24
      sheet: P&L + Cashflow
      document: budget
    Communications costs target:
      cell_ref: V24:AG24
      sheet: P&L + Cashflow
      document: budget
    Professional fees costs actual:
      cell_ref: C25:N25
      sheet: P&L + Cashflow
      document: budget
    Professional fees costs target:
      cell_ref: V25:AG25
      sheet: P&L + Cashflow
      document: budget
    Software costs actual:
      cell_ref: C26:N26
      sheet: P&L + Cashflow
      document: budget
    Software costs target:
      cell_ref: V26:AG26
      sheet: P&L + Cashflow
      document: budget