default_multiplier: 1000

document_keys:
  development:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
    default: budget
  test:
    dashboard: 0Aon_avj5tPqbdHFSNG1HM1JiUThOV1dpeTZ3eTNsa3c
    budget: 0AsEH-bzsP1r8dG9NZlpmc2syOGQzZlN6WmktUDVmN2c
    default: budget
  production:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
    default: budget

cell_lookups:
  2013:
    Reach:
      cell_ref: B1
      sheet: 2013
      document: dashboard
      multiplier: 1
    Bookings:
      cell_ref: B4
      sheet: 2013
      document: dashboard
      multiplier: 1
    Value unlocked:
      cell_ref: B3
      sheet: 2013
      document: dashboard
      multiplier: 1
    KPI percentage:
      cell_ref: B2
      sheet: 2013
      document: dashboard
      multiplier: 1

  2014:
    Network size:
      cell_ref: I24
      sheet: 2014
      document: dashboard
    Members headline:
      cell_ref: I25
      sheet: 2014
      document: dashboard
    Nodes headline:
      cell_ref: I26
      sheet: 2014
      document: dashboard
    Startups headline:
      cell_ref: I27
      sheet: 2014
      document: dashboard
    Affiliates headline:
      cell_ref: I28
      sheet: 2014
      document: dashboard
    Reach:
      cell_ref: B1
      sheet: 2014
      document: dashboard
      multiplier: 1
    Active Reach:
      cell_ref: I21
      sheet: 2014
      document: dashboard
      multiplier: 1
    Passive Reach:
      cell_ref: I22
      sheet: 2014
      document: dashboard
      multiplier: 1
    Bookings:
      cell_ref: B4
      sheet: 2014
      document: dashboard
      multiplier: 1
    Value unlocked:
      cell_ref: B3
      sheet: 2014
      document: dashboard
      multiplier: 1
    KPI percentage:
      cell_ref: B2
      sheet: 2014
      document: dashboard
      multiplier: 1
    Total income:
      cell_ref: G12
      sheet: Summary

    Commercial Bookings:
      actual: W3
      target: AP3
      sheet: Network

    Non-commercial Bookings:
      actual: W4
      target: AP4
      sheet: Network

    Grant Funding:
      actual: U7
      target: AN7
      sheet: General grants

    Research income:
      cell_ref: G15
      sheet: Summary

    Training income:
      cell_ref: G16
      sheet: Summary

    Project income:
      cell_ref: G17
      sheet: Summary

    Network income:
      cell_ref: G18
      sheet: Summary

    Commercial research income:
      actual: W3
      target: AP3
      sheet: Research

    Non-commercial research income:
      actual: W4
      target: AP4
      sheet: Research

    Commercial training income:
      actual: V3
      target: AO3
      sheet: Training

    Non-commercial training income:
      actual: V4
      target: AO4
      sheet: Training

    Commercial projects income:
      actual: W3
      target: AP3
      sheet: Projects

    Non-commercial projects income:
      actual: W4
      target: AP4
      sheet: Projects

    Commercial network income:
      actual: W3
      target: AP3
      sheet: Network

    Non-commercial network income:
      actual: W4
      target: AP4
      sheet: Network

    Headcount:
      actual: D4:O4
      target: V4:AG4
      sheet: OpEx
      multiplier: 1

    Burn:
      actual: C27:N27
      target: V27:AG27
      sheet: P&L + Cashflow

    Commercial people trained:
      actual: E15:P15
      target: X15:AI15
      sheet: Training
      multiplier: 1

    Non-commercial people trained:
      actual: E28:P28
      target: X28:AI28
      sheet: Training
      multiplier: 1

    Partners:
      actual: W7
      target: AP7
      sheet: Network
      multiplier: 1

    Sponsors:
      actual: W9
      target: AP9
      sheet: Network
      multiplier: 1

    Supporters:
      actual: W11
      target: AP11
      sheet: Network
      multiplier: 1

    Startups:
      actual: W18
      target: AP18
      sheet: Network
      multiplier: 1

    Nodes:
      actual: W16
      target: AP16
      sheet: Network
      multiplier: 1

    EBITDA:
      actual: C45:N45
      target: V45:AG45
      sheet: P&L + Cashflow

    Variable costs actual:
      cell_ref: C15:N15
      sheet: P&L + Cashflow

    Variable costs target:
      cell_ref: V15:AG15
      sheet: P&L + Cashflow

    Fixed costs actual:
      cell_ref: C27:N27
      sheet: P&L + Cashflow

    Fixed costs target:
      cell_ref: V27:AG27
      sheet: P&L + Cashflow

    Research costs:
      actual: C11:N11
      target: V11:AG11
      sheet: P&L + Cashflow

    Training costs:
      actual: C12:N12
      target: V12:AG12
      sheet: P&L + Cashflow

    Projects costs:
      actual: C13:N13
      target: V13:AG13
      sheet: P&L + Cashflow

    Network costs:
      actual: C14:N14
      target: V14:AG14
      sheet: P&L + Cashflow

    Staff costs:
      actual: C20:N20
      target: V20:AG20
      sheet: P&L + Cashflow

    Associate costs:
      actual: C21:N21
      target: V21:AG21
      sheet: P&L + Cashflow

    Office and operational costs:
      actual: C22:N22
      target: V22:AG22
      sheet: P&L + Cashflow

    Delivery costs:
      actual: C23:N23
      target: V23:AG23
      sheet: P&L + Cashflow

    Communications costs:
      actual: C24:N24
      target: V24:AG24
      sheet: P&L + Cashflow

    Professional fees costs:
      actual: C25:N25
      target: V25:AG25
      sheet: P&L + Cashflow

    Software costs:
      actual: C26:N26
      target: V26:AG26
      sheet: P&L + Cashflow
