default_multiplier: 1000
default_ytd_method: sum

document_keys:
  development:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
    default: budget
  test:
    dashboard: 0Aon_avj5tPqbdHFSNG1HM1JiUThOV1dpeTZ3eTNsa3c
    budget: 0AsEH-bzsP1r8dG9NZlpmc2syOGQzZlN6WmktUDVmN2c
    default: budget
  production:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
    default: budget

cell_lookups:
  2013:
    Reach:
      cell_ref: B1
      sheet: 2013
      document: dashboard
      multiplier: 1
    Bookings:
      cell_ref: B4
      sheet: 2013
      document: dashboard
      multiplier: 1
    Value unlocked:
      cell_ref: B3
      sheet: 2013
      document: dashboard
      multiplier: 1
    KPI percentage:
      cell_ref: B2
      sheet: 2013
      document: dashboard
      multiplier: 1

  2014:
    Network size:
      cell_ref: I24
      sheet: 2014
      document: dashboard
    Members headline:
      cell_ref: I25
      sheet: 2014
      document: dashboard
    Nodes headline:
      cell_ref: I26
      sheet: 2014
      document: dashboard
    Startups headline:
      cell_ref: I27
      sheet: 2014
      document: dashboard
    Affiliates headline:
      cell_ref: I28
      sheet: 2014
      document: dashboard
    Reach:
      cell_ref: B1
      sheet: 2014
      document: dashboard
      multiplier: 1
    Active Reach:
      cell_ref: I21
      sheet: 2014
      document: dashboard
      multiplier: 1
    Passive Reach:
      cell_ref: I22
      sheet: 2014
      document: dashboard
      multiplier: 1
    Bookings:
      cell_ref: B4
      sheet: 2014
      document: dashboard
      multiplier: 1
    Value unlocked:
      cell_ref: B3
      sheet: 2014
      document: dashboard
      multiplier: 1
    KPI percentage:
      cell_ref: B2
      sheet: 2014
      document: dashboard
      multiplier: 1
    PR Pieces:
      cell_ref: I17
      sheet: 2014
      document: dashboard

    Total income:
      cell_ref: G12
      sheet: Summary

    Grant Funding:
      actual: U7
      annual_target: AN7
      ytd_target: W7:AH7
      sheet: General grants

    Commercial research bookings:
      actual: W14
      annual_target: AP14
      ytd_target: Y14:AJ14
      sheet: Research

    Non-commercial research bookings:
      actual: W23
      annual_target: AP23
      ytd_target: Y23:AJ23
      sheet: Research

    Commercial training bookings:
      actual: V16
      annual_target: AO16
      ytd_target: X16:AI16
      sheet: Training

    Non-commercial training bookings:
      actual: V29
      annual_target: AO29
      ytd_target: X29:AI29
      sheet: Training

    Commercial projects bookings:
      actual: W14
      annual_target: AP14
      ytd_target: Y14:AJ14
      sheet: Projects

    Non-commercial projects bookings:
      actual: W23
      annual_target: AP23
      ytd_target: Y23:AJ23
      sheet: Projects

    Commercial network bookings:
      actual: W14
      annual_target: AP14
      ytd_target: Y14:AJ14
      sheet: Network

    Non-commercial network bookings:
      actual: W20
      annual_target: AP20
      ytd_target: Y20:AJ20
      sheet: Network

    Headcount:
      actual: D4:O4
      annual_target: AG4
      ytd_target: V4:AG4
      sheet: OpEx
      multiplier: 1
      ytd_method: latest

    Burn:
      cell_ref: C27:N27
      sheet: P&L + Cashflow

    Commercial people trained:
      actual: V15
      annual_target: AO15
      ytd_target: X15:AI15
      sheet: Training
      multiplier: 1

    Non-commercial people trained:
      actual: V28
      annual_target: AO28
      ytd_target: X28:AI28
      sheet: Training
      multiplier: 1

    Partners:
      actual: W7
      annual_target: AP7
      ytd_target: Y7:AJ7
      sheet: Network
      multiplier: 1

    Sponsors:
      actual: W9
      annual_target: AP9
      ytd_target: Y9:AJ9
      sheet: Network
      multiplier: 1

    Supporters:
      actual: W11
      annual_target: AP11
      ytd_target: Y11:AJ11
      sheet: Network
      multiplier: 1

    Startups:
      actual: W18
      annual_target: AP18
      ytd_target: Y18:AJ18
      sheet: Network
      multiplier: 1

    Nodes:
      actual: W16
      annual_target: AP16
      ytd_target: Y16:AJ16
      sheet: Network
      multiplier: 1

    EBITDA:
      actual: T33
      annual_target: AM33
      ytd_target: V33:AG33
      sheet: P&L + Cashflow

    Variable costs:
      actual: T15
      annual_target: AM15
      ytd_target: V15:AG15
      sheet: P&L + Cashflow

    Fixed costs:
      actual: T27
      annual_target: AM27
      ytd_target: V27:AG27
      sheet: P&L + Cashflow

    Research costs:
      actual: T11
      annual_target: AM11
      ytd_target: V11:AG11
      sheet: P&L + Cashflow

    Training costs:
      actual: T12
      annual_target: AM12
      ytd_target: V12:AG12
      sheet: P&L + Cashflow

    Projects costs:
      actual: T13
      annual_target: AM13
      ytd_target: V13:AG13
      sheet: P&L + Cashflow

    Network costs:
      actual: T14
      annual_target: AM14
      ytd_target: V14:AG14
      sheet: P&L + Cashflow

    Staff costs:
      actual: T20
      annual_target: AM20
      ytd_target: V20:AG20
      sheet: P&L + Cashflow

    Associate costs:
      actual: T21
      annual_target: AM21
      ytd_target: V21:AG21
      sheet: P&L + Cashflow

    Office and operational costs:
      actual: T22
      annual_target: AM22
      ytd_target: V22:AG22
      sheet: P&L + Cashflow

    Delivery costs:
      actual: T23
      annual_target: AM23
      ytd_target: V23:AG23
      sheet: P&L + Cashflow

    Communications costs:
      actual: T24
      annual_target: AM24
      ytd_target: V24:AG24
      sheet: P&L + Cashflow

    Professional fees costs:
      actual: T25
      annual_target: AM25
      ytd_target: V25:AG25
      sheet: P&L + Cashflow

    Software costs:
      actual: T26
      annual_target: AM26
      ytd_target: V26:AG26
      sheet: P&L + Cashflow
